wallpaper = "/home/usuario/.local/share/backgrounds/omarchy-matte-black-0-ship-at-sea.jpg"

accent = "#e68e0d"
cursor = "#eaeaea"
foreground = "#bebebe"
background = "#121212"
selection_foreground = "#bebebe"
selection_background = "#515151"
color0 = "#333333"
color1 = "#D35F5F"
color2 = "#FFC107"
color3 = "#b91c1c"
color4 = "#e68e0d"
color5 = "#D35F5F"
color6 = "#bebebe"
color7 = "#bebebe"
color8 = "#8a8a8d"
color9 = "#B91C1C"
color10 = "#FFC107"
color11 = "#b90a0a"
color12 = "#f59e0b"
color13 = "#B91C1C"
color14 = "#eaeaea"
color15 = "#ffffff"
mantle = "#121212"


gtk_theme    = "catppuccin-mocha-mauve-standard+default"
cursor_theme = "catppuccin-mocha-dark-cursors"
icon_theme   = "Papirus-Dark"
color_scheme = "prefer-dark"