wallpaper = "/home/usuario/.local/share/backgrounds/omarchy-vantablack-0-dot-hands.jpg"

accent = "#8d8d8d"
cursor = "#ffffff"
foreground = "#ffffff"
background = "#000000"
selection_foreground = "#000000"
selection_background = "#ffffff"
color0 = "#404040"
color1 = "#a4a4a4"
color2 = "#b6b6b6"
color3 = "#cecece"
color4 = "#8d8d8d"
color5 = "#9b9b9b"
color6 = "#b0b0b0"
color7 = "#ececec"
color8 = "#5c5c5c"
color9 = "#a4a4a4"
color10 = "#b6b6b6"
color11 = "#cecece"
color12 = "#8d8d8d"
color13 = "#9b9b9b"
color14 = "#b0b0b0"
color15 = "#ffffff"
mantle = "#000000"


gtk_theme    = "catppuccin-mocha-mauve-standard+default"
cursor_theme = "catppuccin-mocha-dark-cursors"
icon_theme   = "Papirus-Dark"
color_scheme = "prefer-dark"