wallpaper = "/home/usuario/.local/share/backgrounds/omarchy-solitude-1-on-pole.jpg"

accent = "#798186"
cursor = "#cacccc"
foreground = "#cacccc"
background = "#101315"
selection_foreground = "#101315"
selection_background = "#798186"
color0 = "#101315"
color1 = "#565d60"
color2 = "#9fa5a9"
color3 = "#d9dbdc"
color4 = "#798186"
color5 = "#aeaeae"
color6 = "#707070"
color7 = "#cbc2be"
color8 = "#4b4e55"
color9 = "#de6145"
color10 = "#343d41"
color11 = "#c9c2b4"
color12 = "#5d6367"
color13 = "#9a9a9a"
color14 = "#707070"
color15 = "#a5aeb4"
mantle = "#101315"


gtk_theme    = "catppuccin-mocha-mauve-standard+default"
cursor_theme = "catppuccin-mocha-dark-cursors"
icon_theme   = "Papirus-Dark"
color_scheme = "prefer-dark"