wallpaper = "/home/freddy/.local/share/backgrounds/omarchy-catppuccin-2-waves.png"

accent     = "#0078d4"
cursor     = "#ffffff"
foreground = "#e4e4e4"
background = "#1b1d1e"
mantle     = "#141617"
selection_foreground = "#ffffff"
selection_background = "#0078d4"

color0  = "#2a2e32"
color1  = "#e74c3c"
color2  = "#2ecc71"
color3  = "#f1c40f"
color4  = "#0078d4"
color5  = "#9b59b6"
color6  = "#1abc9c"
color7  = "#ecf0f1"
color8  = "#7f8c8d"
color9  = "#c0392b"
color10 = "#27ae60"
color11 = "#f39c12"
color12 = "#2980b9"
color13 = "#8e44ad"
color14 = "#16a085"
color15 = "#ffffff"

gtk_theme    = "Vimix-dark-beryl"
cursor_theme = "Vimix-cursors"
icon_theme   = "Fluent-dark"
color_scheme = "prefer-dark"
